### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Ryan0v0** [mit-han-lab/offsite-tuning#5]
Hi there,

I am currently trying to reproduce the experiments in the paper using your code. However, when running the `quantization.sh` script, I am encountering the following errors:

```
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.self_attn_layer_norm.weight with shape torch.Siz
e([2048]) and dtype torch.float32                                                                                                    
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.self_attn_layer_norm.bias with shape torch.Size(
[2048]) and dtype torch.float32                                                                                                      
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.fc1.weight with shape torch.Size([8192, 2048]) a
nd dtype torch.float32                                                                                                               
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.fc1.bias with shape torch.Size([8192]) and dtype
 torch.float32                                                                                                                       
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.fc2.weight with shape torch.Size([2048, 8192]) a
nd dtype torch.float32                                                                                                               
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.fc2.bias with shape torch.Size([2048]) and dtype
 torch.float32                                                                                                                       
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.final_layer_norm.weight with shape torch.Size([2
048]) and dtype torch.float32                                                                                                        
03/06/2023 21:58:50 - INFO - __main__ - Trainable parameter: model.decoder.layers.23.final_layer_norm.bias with shape torch.Size([204
8]) and dtype torch.float32                                                                                                          
03/06/2023 21:58:55 - INFO - __main__ - ***** Running training *****                                                                 
03/06/2023 21:58:55 - INFO - __main__ -   Num examples = 4700                                                                        
03/06/2023 21:58:55 - INFO - __main__ -   Num Epochs = 10                                                                            
03/06/2023 21:58:55 - INFO - __main__ -   Instantaneous batch size per device = 4                                                    
03/06/2023 21:58:55 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 20                      
03/06/2023 21:58:55 - INFO - __main__ -   Gradient Accumulation steps = 1                                                            
03/06/2023 21:58:55 - INFO - __main__ -   Total optimization steps = 2350                                                            
Traceback (most recent call last):
  File "/nfs-share/wz341/offsite-ori/offsite-tuning/offsite_tuning/run_clm.py", line 498, in <module>
    main()
  File "/nfs-share/wz341/offsite-ori/offsite-tuning/offsite_tuning/run_clm.py", line 353, in main 
_, teacher_zero_shot_perplexity = eval_epoch()
  File "/nfs-share/wz341/offsite-ori/offsite-tuning/offsite_tuning/run_clm.py", line 336, in eval_epoch
    outputs = model(**batch)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forw
ard
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 932, in forwar
d
    outputs = self.model.decoder( 
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 697, in forwar
d
    layer_outputs = decoder_layer(
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 323, in forwar
d
    hidden_states = self.self_attn_layer_norm(hidden_states)
	File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
Traceback (most recent call last):
  File "/nfs-share/wz341/offsite-ori/offsite-tuning/offsite_tuning/run_clm.py", line 498, in <module>
    main()
  File "/nfs-share/wz341/offsite-ori/offsite-tuning/offsite_tuning/run_clm.py", line 353, in main
    _, teacher_zero_shot_perplexity = eval_epoch()
  File "/nfs-share/wz341/offsite-ori/offsite-tuning/offsite_tuning/run_clm.py", line 336, in eval_epoch
    outputs = model(**batch)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forw
ard
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 932, in forward
    outputs = self.model.decoder( 
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 697, in forwar
d
    layer_outputs = decoder_layer(
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 323, in forwar
d
    hidden_states = self.self_attn_layer_norm(hidden_states)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/wz341/anaconda3/envs/offsite/lib/python3.10/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4087765 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4087766 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4087767 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 4087768) of binary: /home/wz341/anaconda
3/envs/offsite/bin/python
```

I am unsure what is causing this issue and would appreciate any assistance in resolving it. Can you please advise on what steps I can take to fix this error and successfully run the `quantization.sh` script?

Thank you for your help!

**Comment by Guangxuan-Xiao** [comment]
Thank you for your interest in our work! What GPU are you using? If your GPU is not Ampere architecture, there is no BF16 datatype. You can change all `bf16` in `quantization.sh` and give it a try.
